### ISSUE TITLE
Lobby command aliases do not work

### ISSUE THREAD

**Issue by fabianmakila** [4drian3d/VLobby#2]
Currently only the first lobby command listed in the config's "commands" section works as expected. Commands listed after that throw the following error:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/44451855/212749717-b9573986-357a-45f3-9dd4-c9f0bb651c49.png">

My configuration:
```toml
# Lobby Commands
commands = ["lobby", "hub"]

[servers]
# Lobby Servers
servers = ["hub"]
# Send Mode
# RANDOM: It will send the player to a random server among the configured ones
# FIRST_AVAILABLE: It will send the player to the first available server
# EMPTIEST: Send the player to the server with the least amount of players
send-mode = "EMPTIEST"

[messages]
succesfully = "<red>You have been successfully sent to the lobby <server>"
error = "<red>You could not be transported to the server <server>"
not-available-server = "<red>No lobby servers available now, try again later"
console-message = "The console could not be teleported to the lobby"
```

# Technical details
Velocity version: `3.2.0-SNAPSHOT (git-697d08ba-b216)`
VLobby version: `1.0.1`
